Milestone 4: To do list
Gardimy/Webpack_setup pull request #2
Opened 2023-05-10 19:37 UTC by Gardimy

In this milestone, I build a simple HTML list of To-Do tasks. I build it using Webpack.

2023-05-10 23:40 UTC, LionRouge1 requested changes
Hi @Gardimy, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![almost](https://media.giphy.com/media/KyBesf8kNT6s88SEgb/giphy.gif)

## Highlights
- Good PR :+1: 
- Good commit :heavy_check_mark: 
- All linters passed :heavy_check_mark: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-10 23:40 UTC, LionRouge1 commented on package.json
>    },
- [ ] Nice work setting up commands for building webpack in production :clap: However it would be nice to also set up command for building in development mode(`npm run start`) to avoid building the all app any times that you make a new change. Therefore kindly make sure basic commands for building Webpack in development mode, production mode are configured.

2023-05-10 23:40 UTC, LionRouge1 commented on src/style.css
- [ ] Nice work populating all the to-dos from an array :+1:  However your list design doesn't look like the [captured video](https://www.youtube.com/watch?v=AcUd-_Yjjqg). Kindly make sure lists are a clone of the part of the minimalist project capture in the video.
### Your design :point_down: 
![Screenshot from 2023-05-10 23-21-30](https://github.com/Gardimy/Webpack_setup/assets/91142432/a89ef955-f9f4-47b6-ab3e-ddd9dfc86aa3)

2023-05-11 02:46 UTC, braincee approved these changes
Hi @Gardimy 👋  , I am @braincee, your Code Reviewer.

Your project is complete! There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! 🎉

![youre-approved-shirley-auto-group](https://user-images.githubusercontent.com/78104544/226852457-95ef4c1d-5d51-4f76-abd8-1fdc06b89e77.gif)

OPTIONAL CHANGES
---

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @braincee._

---

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-05-11 02:58 UTC, merged